Flexible input paths (#59)
Closes #58 

## Usage wildcard
```
./monitor/rtm_gui logs/20260320*
```

## Usage single file
```
./monitor/rtm_gui logs/20260320T162631Z_MarvinUDPServer_rt_loop_0s.tick
```
## Usage folder
```
./monitor/rtm_gui logs
```

## Usage multiple file
```
./monitor/rtm_gui logs/20260320T162631Z_MarvinUDPServer_rt_loop_0s.tick logs/20260320T163609Z_MarvinUDPServer_rt_loop_86s.tick
```

## Added check if file does not exist
```
./monitor/rtm_gui logs/file-does-not-exist.tick                                                                                   
```
```
Error: 'logs/file-does-not-exist.tick' does not exist
```